import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

//wichtig für SEO 
export const metadata = {
    title: "Airpods",                           //* titel im browser
    description: "Generated by create next app",        //* beschreibung im browser
};

export default function RootLayout({ children }) {
    return (
        <html lang="de">
            <body className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} transition-all antialiased`}>
                <SpeedInsights />
                <Analytics />
                {children}
            </body>
        </html>
    );
}
