import "@/app/globals.css";
import AnnouncementBar from "@/components/layout/user/AnnouncementBar";
import Footer from "@/components/layout/user/Footer"
import { Providers } from "@/utils/providers";

//wichtig für SEO 
export const metadata = {
  title: "Airpods",                           //* titel im browser
  description: "Generated by create next app",        //* beschreibung im browser
};

export default function RootLayout({ children }) {
    return (
        <Providers>
            <AnnouncementBar />
            <main>
                {children}
            </main>
            <Footer />
        </Providers>
    );
}
